name: Run SMS Test On Demand

on:
  workflow_dispatch:

jobs:
  sms-test:
    runs-on: ubuntu-latest
    env:
      RUN_SMS_TEST: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Run SMS Test
        run: dotnet test --filter CreateReservationAndSendSmsShould